spring.datasource.url=jdbc:postgresql://localhost:5432/triplana_dev
spring.datasource.username=triplana_user
spring.datasource.password=triplana_pass
spring.session.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=create

app.base-url=http://localhost:5173
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true